ministryofjustice/modernisation-platform-instance-scheduler

instance-scheduler/go.mod, instance-scheduler/go.sum, instance-scheduler/main.go, local-re-run.sh
- Verify the assumed role by calling EC2 client's DescribeInstances
- Use core-shared-services-production profile in local-re-run.sh
=> Use InstanceSchedulerAccess role

instance-scheduler/main.go, instance-scheduler/main_test.go
This PR is to enable API mocking for use in unit tests and to provide an example on how to implement such unit tests.
The above has been achieved through:
1. Introducing aws client's interfaces so that it is possible to mock their APIs (in main.go)
2. Passing client's interfaces into functions rather than defining them inside the functions.
3. Introducing simple unit tests for getSecret and getParameter functions in main_test.go 
More unit tests and more code refactoring will be needed in the future PRs for better code coverage. This is just a mechanism and an example of how it can be achieved.
=> Introducing unit tests.

README.md, instance-scheduler/main.go, instance-scheduler/main_int_test.go, template.yaml
- Added integration test cases: response action, non-member accounts, instance counts
- Accounts mi-platform-development and analytical-platform-data-development cause the main_int_test.go to fail because they appear to lack the InstanceSchedulerAccess role. For now, I have excluded them from the integration test main_int_test.go via the env variable INSTANCE_SCHEDULING_SKIP_ACCOUNTS
- Aligned INSTANCE_SCHEDULING_SKIP_ACCOUNTS env variable with terraform deployment
- Added terraform module deployment to references in README.md
=> Added integration test cases

instance-scheduler/main.go
Related Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2640
Fixing test failues 1:
```
Run Unit Tests of the instance scheduler and see the results of the following test cases:
testing empty action input
testing invalid action input
```
=> Validating action for empty strings and invalid values.

instance-scheduler/Dockerfile, instance-scheduler/go.mod, instance-scheduler/go.sum, instance-scheduler/main.go, instance-scheduler/main_test.go
Relevant Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2640
* Adding a `else` block that actions an instance if the instance-scheduler tag is absent, has an invalid value, an empty value or `default` to align with the [user guidance on instance 
scheduling](https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/instance-scheduling.html#feature-description:~:text=default%20%2D%20Automatically%20stop%20the%20instance%20overnight%20and%20start%20it%20in%20the%20morning.%20Absence%20of%20the%20instance%2Dscheduling%20tag%20will%20have%20the%20same%20effect.)
* Updating go dependencies to the latest version
* Moving `strings.ToLower` into the function code since handler can't be tested while still allowing the action parameter to be …
=> Fixing the causes of failure for the stop action unit test

instance-scheduler/main.go, instance-scheduler/main_test.go
Related Issue: https://github.com/ministryofjustice/modernisation-platform/issues/2640
* Fixing the code for the test action code which didn't increment the number of skipped instances.
* Fixing the expected output of the start action test.
=> Fixing outstanding bugs causing unit test failures

instance-scheduler/go.sum, instance-scheduler/main_int_test.go, template.yaml
As part of https://github.com/orgs/ministryofjustice/projects/17/views/4?pane=issue&itemId=36631217 - this PR is to fix the failing integration tests in the CI/CD to investigate the issues and improve metrics.
As part of the investigation, I'd like to highlight the following issue:
> The CI/CD is tightly coupled to external dependencies and processes, such as our live development and preproduction environments state and our onboarding process (when creating non-member accounts) - Changes in these environments or onboarding a new account can have the unintended side-effect of breaking the instance-schedular CI/CD process. 
I'll create a separate ticket with the above concerns 👆 and add some thoughts on potential remediations to be discussed and prioritised 🙂
=> 🔧 Fix failing integration tests

.github/workflows/build-test-push.yml
This PR  fix's the issues where we have bumped the docker image version and it fails to up load it to the repo. this is due to the version bing hard coded in the workflow
=> Update workflow to docker version bump

instance-scheduler/go.mod, instance-scheduler/go.sum
In order to meet some dependencies for AWS packages the instance scheduler makes use of, this PR bumps the Go version to `1.21` - there are no functional changes, and a local run of `go test -v` completed sucessfully.
=> bumped Go version, ran go mod tidy

instance-scheduler/main_int_test.go
- In relation to https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/issues/138
- To reduce alert noise caused by the static values
- Amended the static values used in the integration tests that compare against the live environment to reduce the noise of these alerts. 
- The alerts mainly cause noise and, in my experience, have not identified issues in the code before deployment - just slowed down the process
- We're keeping the alert for now but just amending the thresholds so they should only alert when something has really gone wrong or the environment has drastically changed
- Ideally, in the future, we can decouple the integration tests from using the live environment state to tests - but there are a few other areas we want to tackle first to build a bit …
=> 🧪 Amend Testing Thresholds to Reduce Noise

instance-scheduler/ec2.go, instance-scheduler/ec2_test.go, instance-scheduler/main.go, instance-scheduler/rds.go, instance-scheduler/rds_test.go, instance-scheduler/utils.go, instance-scheduler/utils_test.go
- In relation to https://github.com/ministryofjustice/modernisation-platform/issues/6687
- Remove some duplication of parsing/validating the Action value
- ♻️ Refactored all logic related to parsing the Action value to the beginning of the script (failing fast) - and ensuring downstream functions use a parsed value instead of the raw value
- 🙈 I've not added unit tests to the main handler in this PR for this specific scenario, requires a bit more work to get the main handler unit testable 🧪
=> ♻️ Refactor `InstanceSchedulingRequest.Action` parsing

.github/workflows/build-test-push.yml, instance-scheduler/main.go, instance-scheduler/main_test.go
- In relation to https://github.com/ministryofjustice/modernisation-platform/issues/6687
- To increase test coverage by unit testing code inside the the `handler` function
- ♻️ Refactored error logic to return an error over using `log.Fatal()` - this should not impact the success/failure status of the lambda since returning a status code of `400` will be considered a failure. This should also increase the verbosity of the error as receiving a `400` will indicate an issue with the request over the generic `500` error.
- ♻️ Refactored the creation of the `Response` Object to the top of the script -  also removed the duplicated creation of this object 🥳
- ✨ Added unit test for `handler` function 
- 🔥 Removed trigger for build-test-push action when PR metadata changes (title, description …
=> ✨ Add Unit Test For Invalid Action

instance-scheduler/ec2.go
- In relation to https://github.com/ministryofjustice/modernisation-platform/issues/6687
- To decouple the responsibilities of the three separate processes: "start", "stop" and "test"
- Refactored all logic related to starting EC2 instances into the `startEc2Instances` function
- Refactored all logic related to stopping EC2 instances into the `stopEc2Instances` function
- Refactored all logic related to testing EC2 instances into the `testEc2Instances` function
- The code currently is highly coupled at a technical level - this PR takes a step towards decoupling which better highlights the three current supported processes and allows the specific business logic of each process to shine through
- The changes implemented are non-functional, so won't affect how the current function operates - …
=> 🫧 Bubble Process Logic Upwards For EC2 Instances

instance-scheduler/ec2.go, instance-scheduler/rds.go
- In relation to https://github.com/ministryofjustice/modernisation-platform/issues/6687
- To decouple the responsibilities of the three separate processes: "start", "stop" and "test"
- Refactored all logic related to starting RDS instances into the `startRDSInstances` function
- Refactored all logic related to stopping RDS instances into the `stopRDSInstances` function
- Refactored all logic related to testing RDS instances into the `testRDSInstances` function
- The code currently is highly coupled at a technical level - this PR takes a step towards decoupling which better highlights the three current supported processes and allows the specific business logic of each process to shine through
- The changes implemented are non-functional, so won't affect how the current function operates - …
=> Bubble Process Logic Upwards For RDS Instances

instance-scheduler/go.mod, instance-scheduler/go.sum
Reverts ministryofjustice/modernisation-platform-instance-scheduler#1204
=> Revert "Bump github.com/aws/smithy-go from 1.20.4 to 1.21.0 in /instance-scheduler"

.github/workflows/build-test-push.yml
I noticed the `build-test-push.yml` workflow `setup-go` stage kept warning about the the following:
```
Warning: Restore cache failed: Dependencies file is not found in /home/runner/work/modernisation-platform-instance-scheduler/modernisation-platform-instance-scheduler. Supported file pattern: go.sum
```
Following this suggestion: https://github.com/actions/setup-go/issues/427#issuecomment-1946115668
I've added a `cache-dependency-path` argument.
Build succeeded without the warning after this.
=> Add go cache-dependency-path

instance-scheduler/Dockerfile
Currently our https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function is failing due to issues with the generated dockerfile (example workflow run [here](https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function) upon further investigation I can lamdba function is failing with the exit code 127 
```
{
"errorType": "Runtime.ExitError",
"errorMessage": "RequestId: 425ef427-c450-48b5-8073-4281fd7f98ef Error: Runtime exited with error: exit status 127"
}
```
further investigation has uncovered that it's an issue with the boostrap in the newly migrated `public.ecr.aws/lambda/provided:al` image (for reference: https://aws.amazon.com/cn/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linu …
=> 🐳  Update Dockerfile

instance-scheduler/main_int_test.go, template.yaml
This PR updates the instance scheduling skip list by adding missing accounts that were causing the `InstanceSchedulerLambdaFunctionPolicy` role to fail in assuming the `InstanceSchedulerAccess` role. These accounts were previously skipped due to being either **member-unrestricted** or opted out by the **members**.
By adding these accounts to the skip list, we ensure that the scheduling process runs smoothly without triggering alarms in the **low-priority channel**, as these accounts should not cause unnecessary notifications.
https://github.com/ministryofjustice/modernisation-platform/issues/8558
https://github.com/ministryofjustice/modernisation-platform/issues/8559
=> Update Instance Scheduling Skip List to Include Missing Accounts

.github/workflows/build-test-push.yml
Skip `Assume InstanceSchedulerLambdaFunctionPolicy role and run GO tests` step in the build-test-push workflow as the same set of tests runs in the `SAM Local Invoke` step.
This reduces the checks from approximately 12misn to 6mis,
=> Improve Unit-Tests

.github/dependabot.yml
This PR updates the dependabot configuration to allow grouping for Github actions and Go dependencies.
=> Add Grouping to Dependabot PRs
